settings:
  title: '监控页'  # 页面标题
  url: 'https://cf-workers-status-page-production.kingxujw.workers.dev'  # 用于发送 Slack 消息的 URL
  logo: logo-192x192.png  # 在 ./public/ 文件夹中的 logo 图片
  daysInHistogram: 30  # 直方图中显示的天数
  collectResponseTimes: true  # 收集来自 CRON 位置的平均响应时间

  allmonitorsOperational: '所有系统正常运行'  # 当所有监控正常时显示的消息
  notAllmonitorsOperational: '部分系统出现问题'  # 当部分监控未运行时显示的消息
  monitorLabelOperational: '正常运行'  # 监控正常时的标签
  monitorLabelNotOperational: '未运行'  # 监控未运行时的标签
  monitorLabelNoData: '无数据'  # 没有数据时的标签
  dayInHistogramNoData: '无数据'  # 直方图中没有数据时显示的内容
  dayInHistogramOperational: '一切正常'  # 直方图中显示监控正常的内容
  dayInHistogramNotOperational: '次事件'  # 直方图中显示监控不正常的内容，格式为 "xx 次事件"

monitors:
  - id: nezha  # 唯一标识符
    name: 哪吒面板  # 监控名称
    description: ''  # 描述（默认=空）
    url: 'https://nz.xujw.us.kg/'  # 需要抓取的 URL
    method: GET  # 请求方法（默认=GET）
    expectStatus: 200  # 正常运行的状态码（默认=200）
    followRedirect: false  # 是否跟随重定向（默认=false）
    linkable: true  # 标题是否可点击为链接（默认=true）

  - id: Sub-Store  # 唯一标识符
    name: Sub-Store订阅转换  # 监控名称
    description: ''  # 描述（默认=空）
    url: 'https://hf.kingxujw.net/'  # 需要抓取的 URL
    method: GET  # 请求方法（默认=GET）
    expectStatus: 200  # 正常运行的状态码（默认=200）
    followRedirect: false  # 是否跟随重定向（默认=false）
    linkable: true  # 标题是否可点击为链接（默认=true）
